size:
  x: 640
  y: 480
# paths normalised to 100 x 100
path:
  - x: 25
    y: 25
  - x: 75
    y: 25
  - x: 75
    y: 75
  - x: 25
    y: 75
opponents:
  - kls: Simple
    speed: 22 #out of 100
    x: 10
    y: 10
    display_name: Alice
    colour: 0xff_ffaaaa
  - kls: Simple
    speed: 24 #out of 100
    x: 90
    y: 10
    display_name: Bob
    colour: 0xff_aaffaa
  - kls: Simple
    speed: 26 #out of 100
    x: 90
    y: 90
    display_name: Charles
    colour: 0xff_aaaaff
  - kls: Simple
    speed: 30 #out of 100
    x: 10
    y: 90
    display_name: Derek
    colour: 0xff_aaaaaa
target: 8

