size:
  x: 640
  y: 480
# paths normalised to 100 x 100
path:
  - x: 25
    y: 25
  - x: 75
    y: 25
  - x: 75
    y: 75
  - x: 25
    y: 75
opponents:
  - kls: Simple
    speed: 100 #out of 100
    x: 25
    y: 75
    display_name: Alice
    colour: 0xff_ffaaaa
  - kls: Turner
    speed: 100 #out of 100
    x: 25
    y: 75
    display_name: Bob
    colour: 0xff_aaffaa
  #- kls: Simple
  #  speed: 87 #out of 100
  #  x: 25
  #  y: 75
  #  display_name: Charles
  #  colour: 0xff_aaaaff
  #- kls: Simple
  #  speed: 88 #out of 100
  #  x: 25
  #  y: 75
  #  display_name: Derek
  #  colour: 0xff_aaaaaa
target: 80

